# Generated by Django 5.1.6 on 2025-06-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=150)),
                ('bookAuthor', models.CharField(max_length=100)),
                ('bookYear', models.IntegerField(max_length=4)),
                ('isbn', models.IntegerField(max_length=13)),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
