# Generated by Django 5.1.6 on 2025-06-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='bookYear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='isbn',
            field=models.IntegerField(),
        ),
    ]
