# Generated by Django 5.1.6 on 2025-06-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBooks', '0002_alter_bookrecord_bookyear_alter_bookrecord_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
