# Generated by Django 5.1.6 on 2025-06-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rentTime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isbn', models.IntegerField()),
                ('issuerId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('rentDate', models.DateTimeField(auto_now=True)),
                ('rentDuration', models.DateTimeField()),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
