# Generated by Django 5.1.6 on 2025-06-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alertTitle', models.CharField(max_length=150)),
                ('alertText', models.TextField()),
                ('alertType', models.CharField(max_length=15)),
                ('alertTimestamp', models.DateTimeField()),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
