# Generated by Django 5.1.6 on 2025-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
