# Generated by Django 5.1.6 on 2025-06-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userTyp', models.CharField(max_length=10)),
                ('userGender', models.CharField(max_length=10)),
                ('userFirstName', models.CharField(max_length=150)),
                ('userSecondName', models.CharField(max_length=150)),
                ('userStreetName', models.CharField(max_length=150)),
                ('userHouseNumber', models.IntegerField()),
                ('userZipCode', models.IntegerField()),
                ('userCityName', models.CharField(max_length=150)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPhone', models.IntegerField()),
                ('userBirthdate', models.DateTimeField()),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
